language: rust
sudo: false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/ # Exclude tags in the style of v1.2.3

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - { os: linux, rust: 1.36.0   }
    - { os: linux, rust: stable   }
    - { os: linux, rust: beta     }
    - { os: linux, rust: nightly  }

script:
  # Modern Java has trouble with sdkmanager: https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre/
  - pushd scripts
  - chmod 755 ./install.sh
  - chmod 755 ./test.sh
  - ./install.sh
  - ./test.sh
  - popd

addons:
  apt:
    packages:
      - openjdk-8-jdk
      - unzip

cache:
  directories:
    - $TRAVIS_HOME/android-sdk-tmp/
