// WARNING:  This file was autogenerated by jni-bindgen.  Any changes to this file may be lost!!!

#![allow(unused_imports)]
#![allow(non_camel_case_types)] // We map Java inner classes to Outer_Inner
#![allow(dead_code)] // We generate structs for private Java types too, just in case.
#![allow(deprecated)] // We're generating deprecated types/methods
#![allow(non_upper_case_globals)] // We might be generating Java style fields/methods
#![allow(non_snake_case)] // We might be generating Java style fields/methods

#[doc(hidden)]
use jni_glue as __jni_bindgen;
#[doc(hidden)]
use jni_glue::__jni_bindgen;

impl __jni_bindgen::ThrowableType for java::lang::Throwable {}
