[[documentation.patterns]]
url_pattern = "https://developer.android.com/reference/{PATH}.html"

[input]
files = ["%LOCALAPPDATA%/Android/Sdk/platforms/android-28/android.jar"]

[output]
path = "src/gen.rs"

[logging]
# verbose = true
