[package]
name = "android-28-sys"
version = "0.0.0"
authors = ["MaulingMonkey <git@maulingmonkey.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
jni-sys = "0.3.0"

[build-dependencies]
bindgen-jni = { path = "../.." }

[features]
default = []
gen = []
