[package]
name = "android-28-sys"
version = "0.0.0"
authors = ["MaulingMonkey <git@maulingmonkey.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
jni-glue = { path = "../../jni-glue" }

[build-dependencies]
bindgen-jni = { path = "../../bindgen-jni" }

[features]
default = []
gen = []
