name: Rust - Nightly

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update nightly && rustup default nightly
    - run: rustup component add rustfmt
    - name: Check fmt
      run: cargo fmt -- --check
    - name: Test
      run: cargo test
